# File: .github/workflows/build-and-push.yml
name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./packages/client
        push: true
        tags: yourusername/salesai-frontend:latest
    - name: Build and push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./packages/server
        push: true
        tags: yourusername/salesai-backend:latest
